### ISSUE TITLE
Version 0.6 crashes on startup

### ISSUE THREAD

**Issue by Gronglegrowth** [Mithion/FXBuildup#3]
When attempting to load the game with FXBuildup 0.6, it will crash (no crashreport is generated, though), with the following log error:
`[main/FATAL] [ne.mi.fo.la.MavenVersionAdapter/]: Failed to parse version spec [1.18.2)
org.apache.maven.artifact.versioning.InvalidVersionSpecificationException: Single version must be surrounded by []: [1.18.2)`

**Comment by Mithion** [comment]
Fixed for version 0.61 - sorry about that!
